[package]
name = "nanom-derive"
version = "0.1.4"
edition = "2021"
description = "derive macros for nanom"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.7.1"
proc-macro2 = "1.0.93"
syn = "2.0.96"
synstructure = "0.13.1"
